SELECT ROWNUM() NPP, smd.ID, smd.DTSTAMP, smd.DATEPOST,
smd.MSG_ID, CAST(smd.SUBJECT AS SQL_CHAR) SUBJECT, CAST(smd.SUBJ_ADRESAT AS SQL_CHAR) SUBJ_ADRESAT, smd.SUBJ_TYPE, smd.DOC_STATUS, smd.SENT,
CAST(smd.NAME AS SQL_CHAR) NAME, smd.SMDOCODE,
smd.MSG_TYPE, smd.MSG_ACKNOW, smd.ACK_MSG_ID, smd.ACK_TYPE, smd.ADR_REGNUMBER, smd.ADR_REGDATE, smd.MY_REGNUMBER, smd.MY_REGDATE,
smd.KIND, smd.CONFIDENT, smd.FLAG, ' ' INFO, smd.TEXT, smd.SUBJ_ERROR, smd.ERROR_TEXT, smd.SUBJ_SYSTEM, smd.COUNT_POST,
IIF(smd.msg_type=0,ISNULL(smd.ACK_TYPE,0)+10,smd.DOC_STATUS) as DOC_ACK_TYPE
FROM SMDOPost smd WHERE smd.msg_type<>0/*END*/    ORDER BY smd.ID DESC
