
{$WARN UNIT_PLATFORM OFF}


// доступность экспорта в форме SQL
//{$DEFINE ENABLE_EXPORT}

{$DEFINE EHLIB3}

{$DEFINE USE_SCRIPT}
{$DEFINE USE_LOGFILE}
{$DEFINE USE_NEW_SPR}
{$DEFINE VER_LOOKUP_2}
{$DEFINE DATASET_AS_ADS}

{$DEFINE UPDATE_SYNA}

{$DEFINE RO_SCRIPT}

{$DEFINE NOT_USE_REPORT}
//{$DEFINE USE_FR2}
//{$DEFINE USE_FR3}

// компил€ци€ с возможностью работы с √»—”Ќ
//{$DEFINE GISUN}
// верси€ дл€ тестировани€ с √»—”Ќ
//{$DEFINE TEST_GISUN}

{$DEFINE UPDATEPROG}

// компил€ци€ дл€ программы «ј√—
//{$DEFINE ZAGS}

// компил€ци€ дл€ программы ќчередники
//{$DEFINE OCHERED}

// компил€ци€ дл€ программы LAIS
//{$DEFINE LAIS}

// компил€ци€ дл€ программы ∆ ’
//{$DEFINE GKH}
 
// возможность использовани€ шаблонов
//{$DEFINE USE_TEMPLATE}
//{$DEFINE USE_WORD}

// Ётот параметр условной компил€ции необходимо использовать при подключении
// подсистемы к общему модулю
//{$DEFINE in_sel}

//{$DEFINE OBR_GRAG}



