   ADD COLUMN  OTEC_STATUS CIChar( 1 )
   ADD COLUMN  OTEC_IDENTIF CIChar( 14 )
   ADD COLUMN  OTEC_Familia CIChar( 50 )
   ADD COLUMN  OTEC_Name CIChar( 30 )
   ADD COLUMN  OTEC_Otch CIChar( 30 )
   ADD COLUMN  OTEC_DateR Date
   ADD COLUMN  OTEC_GRAG Integer
   ADD COLUMN  OTEC_B_RESP Logical
   ADD COLUMN  OTEC_GOSUD Integer
   ADD COLUMN  OTEC_B_OBL Logical
   ADD COLUMN  OTEC_OBL CIChar( 30 )
   ADD COLUMN  OTEC_RAION CIChar( 30 )
   ADD COLUMN  OTEC_B_GOROD Short
   ADD COLUMN  OTEC_GOROD CIChar( 30 )
   ADD COLUMN  OTEC_GOROD_R CIChar( 70 )
   ADD COLUMN  OTEC_DOM CIChar( 10 )
   ADD COLUMN  OTEC_KORP CIChar( 7 )
   ADD COLUMN  OTEC_KV CIChar( 10 )
   ADD COLUMN  OTEC_WORK Memo

   ADD COLUMN  MAT_STATUS CIChar( 1 )
   ADD COLUMN  MAT_IDENTIF CIChar( 14 )
   ADD COLUMN  MAT_Familia CIChar( 50 )
   ADD COLUMN  MAT_Name CIChar( 30 )
   ADD COLUMN  MAT_Otch CIChar( 30 )
   ADD COLUMN  MAT_DateR Date
   ADD COLUMN  MAT_GRAG Integer
   ADD COLUMN  MAT_B_RESP Logical
   ADD COLUMN  MAT_GOSUD Integer
   ADD COLUMN  MAT_B_OBL Logical
   ADD COLUMN  MAT_OBL CIChar( 30 )
   ADD COLUMN  MAT_RAION CIChar( 30 )
   ADD COLUMN  MAT_B_GOROD Short
   ADD COLUMN  MAT_GOROD CIChar( 30 )
   ADD COLUMN  MAT_GOROD_R CIChar( 70 )
   ADD COLUMN  MAT_DOM CIChar( 10 )
   ADD COLUMN  MAT_KORP CIChar( 7 )
   ADD COLUMN  MAT_KV CIChar( 10 )
   ADD COLUMN  MAT_WORK Memo
