SELECT DOC_ID, REG_IND, REG_DATE, DOC_TYPE, DELIV_KIND, SIGN_ORG, SIGN_NAME, NUM_LIST, DOC_KIND, CAST(CONTENT AS SQL_CHAR) CONTENT, IDEN_DATE, IDEN_TEXT, DOC_DATE, DOC_IND, REQ_DATE, REQ_IND, TRIM(s.SMDOCODE+' '+s.NAME) SIGN_ORG_NAME, POST_ID, RES_MAN, EXEC_MAN
FROM DocMain d
LEFT JOIN —прћест–аботы s ON s.id=d.sign_org
WHERE doc_type=4
ORDER BY REG_DATE Desc, REG_NUM Desc