DELETE FROM БазаСвойствОбъектов
  WHERE date_fiks='1899-12-30' and 
  (POKAZ='BIG_ENIMAL' or POKAZ='KOROVA' or POKAZ='TELKI1' or POKAZ='SVINI' or
   POKAZ='SVINOMAT' or POKAZ='OVCI' or POKAZ='OVCIMAT' or POKAZ='KOZI' or 
   POKAZ='KOZIMAT' or POKAZ='LOSHADI' or POKAZ='PTICA' or POKAZ='KROL' or 
   POKAZ='PCHELI' or POKAZ='NUTRII' or POKAZ='PESCI' or POKAZ='FREDKI' or
   POKAZ='PUSH1' or POKAZ='KOSHKI' or POKAZ='SOBAKI' or POKAZ='ADD1')
        
